// Generated by delombok at Wed Sep 06 01:34:15 AST 2017

public class ToggleTest {
    private String __evaluateSwitch(String name) {
        return ":C";
    }

    private int index = 0;

    public boolean getToggleState(String toggleName) {
        return index++ % 2 == 0;
    }

    public void method1(Object a) {
        return dispatcher_for_test(a);
    }

    //@ToggleOn("ToggleName")
    public void method10(Object a) {
        System.out.println("Hello Kitty!");
    }

    //@ToggleOff("ToggleName")
    public void method2() {
        System.out.println("Hello World!");
    }

    //@ToggleOn("ToggleName2")
    public void method3() {
        System.out.println("Hello Kitty!");
    }

    //@ToggleOff("ToggleName2")
    public void method4() {
        System.out.println("Hello World!");
    }

    public static void main(String[] args) {
        ToggleTest test = new ToggleTest();
        test.method1(null);
        test.method1(null);
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    private void method1$_old(Object a) {
        if (true) {
            System.out.println("Hello Kitty!");
            method1(a);
            return;
        }
        System.out.println("Hello Kitty!");
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    private void dispatcher_for_test(Object a) {
        java.lang.String test_value = __evaluateSwitch("test");
        if ("test".equals(test_value)) {
            method1$_old(a);
            return;
        }
        throw new java.lang.RuntimeException("Uncovered case reached");
    }
}
